### ISSUE TITLE
Users cant configure 2FA

### ISSUE THREAD

**Issue by Jamsterz** [Part-DB/Part-DB-server#717] opened 2024-09-27 04:02 UTC
Permissions issue only allows members of the Admins group to configure 2FA.

Other users should be able to configure 2FA

**Comment by Jamsterz** [comment] 2024-10-01 13:00
It lets you put in the code and does nothing after. If you put in the wrong code it tells you it’s wrong but putting in the correct code does nothing. Changing the users groups from Users to Admins the correct code adds the Authenticator successfully

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jbtronics** [comment] 2024-10-13 18:14
This was caused by an constraint that should prevent users to lockout themselves accidentally, which was triggered here for the wrong reason. This is fixed with the latest commits.

**Closed** 2024-10-13 18:29 UTC
Labels: bug
