### ISSUE TITLE
Only last added price get saved by part creation

### ISSUE THREAD

**Issue by PhilippBleimund** [Part-DB/Part-DB-server#219] opened 2023-02-19 13:09 UTC
**Describe the bug**
When creating a new part and adding more than one price information (eg. 10: 0,1$ , 20: 0,08$) only the last added price information gets saved when creating the part. Editing the part afterwards functions completely normal without problems.

**To Reproduce**
1. Go to '+ Part'
2. Click on 'shopping information'
3. Add new supplier
4. Add multiple price points

**Expected behavior**
That the inputted values are saved.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/77382879/219949209-2008ebd9-74e8-4835-8cc7-5fee90b44f63.png)
After:
![image](https://user-images.githubusercontent.com/77382879/219949291-0cbb7e20-8b72-451e-b3fb-62bb10a298ec.png)

**Server Side**
- Part-DB Version: 1.0.0-beta.2-dev (commit: d03586d9d57648d57a200d15355ff4e59425bb08)
- PHP Version: 8.1.15
- Database Server sqlLite

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 109.0.5414.121

**Comment by jbtronics** [comment] 2023-02-20 11:43
This problem only occurred, when you created both a new order information and new price information inside it (which is always the case when creating new parts). This was caused by some issue in the implementation of the nested CollectionTypes, which caused the inner fields to all get the same name.

The issue is fixed in Release 1.0.1

**Closed by jbtronics** 2023-02-20 11:43 UTC
Labels: bug
