### ISSUE TITLE
HTML attachment stored as txt

### ISSUE THREAD

**Issue by mase76** [Part-DB/Part-DB-server#251] opened 2023-03-19 19:13 UTC
Hi,
I have added some PCBs to the inventory, and also wanted to add interactive boms in html as attachment. However these files are stored as txt instead of html. They are created with the interactive bom addon of Kicad. I have created a filetype with .html extension before.

**Comment by jbtronics** [comment] 2023-03-19 21:16
This is intended behavior for public reachable attachments (non private attachments) and a security measure. All file extensions which are somehow specially treated by browsers or the server (like HTML, CSS, JS  or PHP files) get saved and served as txt files, which are not parsed by the browser. Otherwise malicious users could use the attachment uploads to sneak malicious code on the server or circumvent security measurements like the content security policy.

If you need to upload these kind of files you have to do this as private attachments (just select the checkbox when creating the attachment), then Part-DB will serve the file (and not the server) and can set certain headers to prevent misuse while maintaining the filename.

However the browser will still just show the content of the file or download it (then with the correct file extension). You still need to download the file first to view it in the browser (but that should be just one click more, so should not be a big issue).

Closing this as non fix, as this behavior can not be changed for security reasons.

**Closed** 2023-03-19 21:16 UTC
